FROM node:10-alpine as prod
ARG CREATED_DATE=not-set
ARG SOURCE_COMMIT=not-set
ARG DOCKER_DESTINATION=not-set
ARG LOG_LEVEL=error
ARG PORT=3000
ARG NODE_TARGET=GKE
LABEL com.mck.image.authors=hemanth.tummala@mckesson.com
LABEL com.mck.image.created=$CREATED_DATE
LABEL com.mck.image.revision=$SOURCE_COMMIT
LABEL com.mck.image.title=""
LABEL com.mck.image.url=${DOCKER_DESTINATION}
LABEL com.mck.image.source=""

ENV NODE_ENV production
ENV LOG_LEVEL $LOG_LEVEL
ENV NODE_TARGET $NODE_TARGET
ENV PORT $PORT
RUN apk add --no-cache tini bash
WORKDIR /node
COPY package*.json ./
RUN mkdir app && chown -R node:node .
USER node
RUN npm install --only=production \
    && npm cache clean --force
WORKDIR /node/app
COPY --chown=node:node . .
EXPOSE ${PORT}
ENTRYPOINT [ "tini","--" ]
CMD ["node","index.js"]
## local
FROM prod as local 
ENV NODE_ENV local
ENV LOG_LEVEL info
RUN npm install --only=development \
    && npm cache clean --force
